1. What does Pandas stand for? 
# #An open-source Python package that is most widely used for data science/data analysis and machine learning tasks.

2. What are the 2 collections used in Pandas?\
# #Series and Data Frame
3. Name 4 things Pandas can do for us.
# #open files (csv,sql,exel)load
# manipulate
# prepare
# model

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
inplace 
5. What is a CSV?
# #comma separated files
6. When cleaning data what values do we not like in our data?
# #null(dropna) duplicates (drop.duplacates)


In [1]:
#7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
import numpy as np
import copy
#8
#my_list = np.arange(12).reshape((2, 3 ,2))
#my_copylist = copy.deepcopy(my_list)

#print('Original \n', my_list)
#print('\n copy \n', my_copylist)

my_array = np.linspace(0,20,6)

print(my_array)

[ 0.  4.  8. 12. 16. 20.]


In [7]:
#9
new_array1 = ([[ 25, 16] ],
              [[11, 2], [13, 4]],
              [ [7, 81], [5, 6], [11, 12]])

a, b, c = new_array1
print('a = ', a)
print('b = ', new_array1)
print('c = ', c)
 
cArray = np.concatenate((a, b, c), axis = 0)
print('\nconcanate \n', cArray)

#11
sortedAAAArray = np.sort(cArray, axis =None)
print(sortedAAAArray)

a =  [[25, 16]]
b =  ([[25, 16]], [[11, 2], [13, 4]], [[7, 81], [5, 6], [11, 12]])
c =  [[7, 81], [5, 6], [11, 12]]

concanate 
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[ 2  4  5  6  7 11 11 12 13 16 25 81]


In [8]:
#12
import pandas as pd

Ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name = 'Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name = 'Quantity' )
Unit = pd.Series(['cups', 'cup', 'large', 'can'], name ='Unit')
df =pd.concat([Ingredients, Quantity, Unit], axis = 1)
print(df)


  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [9]:
#13
Data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
        }
studentData = pd.DataFrame(Data)
print(studentData)
#14
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['Deserts'] = deserts
print(studentData)

#15
studentData.sort_values(by = ['Name', 'address'], inplace=True)
print('\nStudent Data sorted..\n', studentData)


      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  

Student Data sorted..
       Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar 

In [10]:
#16
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')

In [11]:
#17

vegetables = pd.DataFrame({'Cucumbers': [14],
                           'Tomatoes': [11],
                           'Onion': [1]}, index=['Quantity1', 'Quantity2', 'Quantity3'])

vegetables.to_csv('Vegetables')